name: PR title check
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  title_format:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Check for JIRA id in PR title
        run: |
          #!/bin/bash
          echo "PR title is \"$PR_TITLE\""
          if [[ ! $PR_TITLE =~ ^\[[A-Z0-9]+-[0-9]+\] ]];then
            echo "PR title must start with JIRA ticket. e.g. \"[BFF-123] $PR_TITLE\""
            exit 1
          fi
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
