name: "Pull Request Triage"

on: [pull_request]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/XS'
          xs_max_size: '30'
          s_label: 'size/S'
          s_max_size: '100'
          m_label: 'size/M'
          m_max_size: '250'
          l_label: 'size/L'
          l_max_size: '500'
          xl_label: 'size/XL'
          fail_if_xl: 'false'
          message_if_xl: 'This PR exceeds the recommended size of 500 lines. Please make sure you are NOT addressing multiple issues with one PR. Note this PR might be rejected due to its size.'
